CC := gcc

# .PHONY:fopen_test
fopen_test:fopen_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

# .PHONY:fclose_test
fclose_test:fclose_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputc_test:fputc_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputs_test:fputs_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fprintf_test:fprintf_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgets_test:fgets_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fscanf_test:fscanf_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

system_call_test:system_call_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@